apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-b-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-b
  template:
    metadata:
      labels:
        app: backend-b
    spec:
      containers:
        - name: backend-b-container
          image: backend-b:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
