apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-a-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-a
  template:
    metadata:
      labels:
        app: backend-a
    spec:
      containers:
        - name: backend-a-container
          image: backend-a:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
